#!/dis/sh
cd /dis; cp -x accent acme.dis acme.dist cyrillic ecvar findguide frotz g gorn greek grepdiff guide indent kanban keyboard ligature lsdo map mapmk mapsh mas mistype mkdo monnum monthnamenum nb nbdoc nbend nbnew nocr paths pos redo redoer repare resum so stardate todate twit twitter unindent /acmecat/dis
rm -f /acmecat/lib/do/*; cp -x /lib/do/* /acmecat/lib/do
rm -f /acmecat/lib/sed/*; cp -x /lib/sed/* /acmecat/lib/sed
rm -f -r /acmecat/nb/pub/*; cp -x -r /nb/pub/* /acmecat/nb/pub
echo /nb/pub/nbindex > /acmecat/nb/nbindexes
