#!/dis/sh
/lib/sed/guide
:, |nocr
:, |sed '/^nb /s, complete , _complete ,'
:, |sed 's,,,'
:, |sed 's,$,,'
:, |sed 's,([^])$,\1,;s,^$,,'
:, |sed 's,,,g'
:, |sed 's,^nb ,nb acme ,'
:, |sort -r
Goog eucalyptus koala
cd /nb; du -a | grep '\.do$' | sed 's,.* +,,'
chmod +x mkdo
cp -x indent unindent
echo; map 'ls -ltr' map mas a b
findguide '(lang|tool)'
findguide acmesac
findguide me
findguide perl
if {pos ls ths} {echo ok} {echo not ok}
if {pos pwd} {echo ok} {echo not ok}
kanban bcprw ec/
kanban rally
kanban ready
kanban rim | grep plugin | grep -v plugins
kanban todate
kanban working
ls -ltr
map(1)
mkdo
nb -i calendar
nb acmesac
nb guide
nb keyboard
nb people
nb perl
nb toread
pos df -h .
pos which which
redo
stardate | sed 's,\..*,,'
todate
tweet @catenate Testing command-line twitter client ttytter running in cygwin, called from acme.
twit catenate
twitter @catenate
twitter catenate
unicode ' '
unicode '#'
win units
|keyboard
|ligature
|nocr |nobl |fmt
|sed 's,,,'
|sed 's,^,	,'
|sed 's,^[ 	]+,,'
|sort|uniq
|tr '[A-Z]' '[a-z]'
|tr 'anihdyujgcvpmlsrxo;kf.,bt/' 'abcdefghijklmnopqrstuvwxyz'

rm -rf scan
cp -r -x scan me

diff /nb/pub/acmesacs/dis/redoer redoer 
