#!/dis/sh
(f re) = $*

if {~ $#* 0} {
	f = abcrpnd
	re = .
}

if {~ $#* 1} {
	re = $f
	f = abcrpnd
}

if {~ $f '*a*'} {
	nb -x ' _archive ' | grep $re | sed 's,'^`{pwd}^'/,,'
}

if {~ $f '*b*'} {
	nb -x ' _backlog ' | grep $re | sed 's,'^`{pwd}^'/,,'
}

if {~ $f '*c*'} {
	nb -x ' _complete ' | grep $re | sed 's,'^`{pwd}^'/,,'
}

if {~ $f '*r*'} {
	nb -x ' _roadmap ' | grep $re | sed 's,'^`{pwd}^'/,,'
	count=`{nb -x ' ready ' | grep $re | sed 's,'^`{pwd}^'/,,' | grep -v 'todate:' | wc -l}
	load expr 
	if {~ ${expr $count 13 gt} 1} {echo too many}
}

if {~ $f '*p*'} {
	nb -x ' _ping ' | grep $re | sed 's,'^`{pwd}^'/,,'
}

if {~ $f '*n*'} {
	nb -x ' _next ' | grep $re | sed 's,'^`{pwd}^'/,,'
	count=`{nb -x ' _next ' | grep $re | sed 's,'^`{pwd}^'/,,' | grep -v 'todate:' | wc -l}
	load expr 
	if {~ ${expr $count 5 gt} 1} {echo too many}
}

if {~ $f '*d*'} {
	nb -x ' _doing ' | grep $re | sed 's,'^`{pwd}^'/,,'
	count=`{nb -x ' _doing ' | grep $re | sed 's,'^`{pwd}^'/,,' | grep -v 'todate:' | wc -l}
	load expr 
	if {~ ${expr $count 2 gt} 1} {echo too many}
}

exit 0
