#!/dis/sh
res = $*
refs = `{nb $res | sed 's,: .*,,'}

load string
apply {
	ref = $1
	(file line) = `{echo ${splitr $ref ':'}}
	file = `{echo $file | sed 's,:$,,'}
	sed -n $line^',/^nb/p' $file | sed '$d'
} $refs
